aug_ver: 4
augmentations: []
batch_size: 32
dataset_name: train_images_512
do_mixup: true
duration: 10
early_stop_epoch: 10
embed_dim: 128
input_feature: logmel
loss_fn: focal_clip_max_v2
lr: 1.0e-05
lr_max: 0.001
lr_min: 1.0e-05
max_epoch: 30
model: bird_sed_b1
model_path: ''
num_workers: 2
pretrained: true
scheduler: CosineAnnealingLR
training_year: '2021_2022'
use_class_weight: false
